import Link from 'next/link';
import '../globals.css';
import { Roboto_Slab } from 'next/font/google';
import { getUserDataFromToken } from '@/utils/tokenUtil';
import Logout from '@/components/Logout';

const roboto_slab = Roboto_Slab({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const user = getUserDataFromToken();
  
  return (
    <html lang="en">
      <body className={`${roboto_slab.className} text-slate-600`}>
        <header>
          <div className='container mx-auto px-3 py-4'>
            <div className='flex items-center'>
              <h1 className='text-3xl font-bold'><Link className='text-cyan-400' href={'/'}>NextBlog</Link></h1>

              <ul className='flex ml-auto space-x-4 font-semibold text-md'>
                <li><Link className='hover:text-cyan-400 text-slate-600 transition-all' href={'/'}>About Me</Link></li>
                <li><Link className='hover:text-cyan-400 text-slate-600 transition-all' href={'/'}>Blog</Link></li>
                <li><Link className='hover:text-cyan-400 text-slate-600 transition-all' href={'/'}>Contact</Link></li>
                { !user && <li><Link className='hover:text-cyan-400 text-slate-600 transition-all' href={'/register'}>Register</Link></li>}
                { !user && <li><Link className='hover:text-cyan-400 text-slate-600 transition-all' href={'/login'}>Login</Link></li>}
                { user && <li><Link className='hover:text-cyan-400 text-slate-600 transition-all' href={'/admin'}>Admin</Link></li>}
                { user && <li><Link className='hover:text-cyan-400 text-slate-600 transition-all' href={'/logout'}>Logout</Link></li>}
              </ul>
            </div>
          </div>
        </header>

        { user === 'token_expired' && <Logout /> } {/* Logout if session expired */}

        <main className='py-24'>
          <div className='container mx-auto px-3'>
            {children}
          </div>
        </main>
        <footer>
          <div className='container mx-auto px-3 py-4'>
            <div className='flex items-center justify-center text-center'>
              &copy; NextBlog {new Date().getFullYear()}. All rights reserved
            </div>
          </div>
        </footer>
      </body>
    </html>
  )
}
